// This file is @generated by prost-build.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SenderSubscription {
    #[prost(string, optional, tag="1")]
    pub sender_jid: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint32, optional, tag="2")]
    pub pid: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag="3")]
    pub ssrc: ::core::option::Option<u32>,
    #[prost(uint32, repeated, packed="false", tag="4")]
    pub ssrcs: ::prost::alloc::vec::Vec<u32>,
    #[prost(enumeration="StreamLayer", optional, tag="5")]
    pub stream_layer: ::core::option::Option<i32>,
    #[prost(enumeration="PayloadType", optional, tag="6")]
    pub payload_type: ::core::option::Option<i32>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SenderSubscriptions {
    #[prost(message, repeated, tag="1")]
    pub senders: ::prost::alloc::vec::Vec<SenderSubscription>,
}
// VoIP SenderSubscriptions - STUN 0x4000 attribute
// Reverse engineered from WhatsApp WASM (Wa__Voip__SenderSubscriptions)

#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum StreamLayer {
    Audio = 0,
    VideoStream0 = 1,
    VideoStream1 = 2,
    HbhFecClientToServer = 3,
    HbhFecServerToClient = 4,
    AppDataStream0 = 5,
    LiveTranscriptionStream0 = 6,
}
impl StreamLayer {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Audio => "STREAM_LAYER_AUDIO",
            Self::VideoStream0 => "STREAM_LAYER_VIDEO_STREAM_0",
            Self::VideoStream1 => "STREAM_LAYER_VIDEO_STREAM_1",
            Self::HbhFecClientToServer => "STREAM_LAYER_HBH_FEC_CLIENT_TO_SERVER",
            Self::HbhFecServerToClient => "STREAM_LAYER_HBH_FEC_SERVER_TO_CLIENT",
            Self::AppDataStream0 => "STREAM_LAYER_APP_DATA_STREAM_0",
            Self::LiveTranscriptionStream0 => "STREAM_LAYER_LIVE_TRANSCRIPTION_STREAM_0",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "STREAM_LAYER_AUDIO" => Some(Self::Audio),
            "STREAM_LAYER_VIDEO_STREAM_0" => Some(Self::VideoStream0),
            "STREAM_LAYER_VIDEO_STREAM_1" => Some(Self::VideoStream1),
            "STREAM_LAYER_HBH_FEC_CLIENT_TO_SERVER" => Some(Self::HbhFecClientToServer),
            "STREAM_LAYER_HBH_FEC_SERVER_TO_CLIENT" => Some(Self::HbhFecServerToClient),
            "STREAM_LAYER_APP_DATA_STREAM_0" => Some(Self::AppDataStream0),
            "STREAM_LAYER_LIVE_TRANSCRIPTION_STREAM_0" => Some(Self::LiveTranscriptionStream0),
            _ => None,
        }
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum PayloadType {
    Media = 0,
    Fec = 1,
    Nack = 2,
    AppData = 3,
    HbhFec = 4,
}
impl PayloadType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Media => "PAYLOAD_TYPE_MEDIA",
            Self::Fec => "PAYLOAD_TYPE_FEC",
            Self::Nack => "PAYLOAD_TYPE_NACK",
            Self::AppData => "PAYLOAD_TYPE_APP_DATA",
            Self::HbhFec => "PAYLOAD_TYPE_HBH_FEC",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PAYLOAD_TYPE_MEDIA" => Some(Self::Media),
            "PAYLOAD_TYPE_FEC" => Some(Self::Fec),
            "PAYLOAD_TYPE_NACK" => Some(Self::Nack),
            "PAYLOAD_TYPE_APP_DATA" => Some(Self::AppData),
            "PAYLOAD_TYPE_HBH_FEC" => Some(Self::HbhFec),
            _ => None,
        }
    }
}
